'''
Date: 2020.04.02
@author: Clayton
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Result:
Runtime: 20 ms, faster than 99.54% of Python3 online submissions for Find the Difference.
Memory Usage: 14.1 MB, less than 10.00% of Python3 online submissions for Find the Difference.
'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        sSum = sum(map(lambda x: ord(x), s))
        tSum = sum(map(lambda x: ord(x),t))
        return chr(tSum-sSum)